### ISSUE TITLE
License

### ISSUE THREAD

**Issue by scaui0** [benbotto/rubiks-cube-cracker#11]
Hello,
I'm working on a project that solved a Rubik's Cube using Python. My Problem is that the generation of the pattern databases would take more than 1000 years. So I decided to use an existing one and just program the rest. Than I found your project with pattern database. Since it has no licence, I am not allowed to use any code of it. Could you please add a license? Or shouldn't I use it?

Thanks in advance
scaui0

**Comment by benbotto** [comment]
Hi scaui0.  I can probably add a license at some point.  I'd accept a PR, too.  Consider it MIT, I reckon.

**Comment by scaui0** [comment]
Thank you!
