### ISSUE TITLE
From Another Program

### ISSUE THREAD

**Issue by karaketir16** [benbotto/rubiks-cube-cracker#3]
Is it possible to use this as library in another c++ program?

Or is it possible to run this program as just giving the scramble or positions of cubies as input and solution as output?
Like 
```
./solver < scramble.txt  > solution.txt
./solver < cube.txt  > solution.txt
```

**Comment by karaketir16** [comment]
I need optimal solutions for Rubik's Cube for a project. Not a real project for now :)

Maybe I will write my own code for algorithm, it looks fun.

**Comment by benbotto** [comment]
It would be possible to use this as a library, but it's not set up for that scenario at present.

The program does not support taking in a scrambled cube and printing out the solution.  It's a virtual Rubik's Cube and doesn't really help with solving physical cubes.  Accepting a scramble as input has been on the bucket list for a while, though (PRs welcome!).
