### ISSUE TITLE
Glitches at startup and when rotating faces

### ISSUE THREAD

**Issue by mehdibenk** [benbotto/rubiks-cube-cracker#9]
I get this glitch at startup:

![image](https://github.com/user-attachments/assets/86729b0b-603d-43ef-86eb-007f836a9fce)

After doing a single U rotation :
![image](https://github.com/user-attachments/assets/1010dded-d341-4d7c-ae8d-a9cc7130d9a0)

After doing a combination of F, R and U rotations :
![image](https://github.com/user-attachments/assets/de8612b1-5093-49ca-88d6-eb3135962714)

Do you have and idea what could be the cause ?

I compiled the app using QtCreator on linuxmint 20.1
glew version: 2.1.0-4
glfw version: 3.3.2-1

**Comment by mehdibenk** [comment]
The problem was solved by using the recommended versions of GLM, GLEW and GLFW as mentioned in the following instructions :

[https://github.com/benbotto/rubiks-cube-cracker/blob/master/BUILDING.md#without-docker-opengl-dependencies](url)

**Comment by mehdibenk** [comment]
The problem was solved by using the recommended versions of [GLM](https://github.com/g-truc/glm/releases/download/0.9.8.5/glm-0.9.8.5.zip) (0.9.8.5), [GLEW](https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0.zip) (2.2.0) and [GLFW](https://github.com/glfw/glfw/releases/download/3.3.3/glfw-3.3.3.zip) (3.3.3) as mentioned in the following instructions :

[https://github.com/benbotto/rubiks-cube-cracker/blob/master/BUILDING.md#without-docker-opengl-dependencies](https://github.com/benbotto/rubiks-cube-cracker/blob/master/BUILDING.md#without-docker-opengl-dependencies)

**Comment by benbotto** [comment]
Glad you figured it out.  I actually tried building the program using the library versions you mentioned in your first post--GLEW 2.1.0 and GLFW 3.3.2--and didn't not experience the issue.  I didn't try with alternate versions of GLM, though.  What version of GLM were you using originally?

**Comment by mehdibenk** [comment]
I used the `libglm-dev` package that comes with two different linuxmint installations : 

- linuxmint 20.1 64bit codename ulyssa :  `libglm-dev` version 0.9.9.7+ds-1 
[https://packages.ubuntu.com/focal/libglm-dev](https://packages.ubuntu.com/focal/libglm-dev)


- linuxmint 22 64bit codename wilma : `libglm-dev` version 0.9.9.8+ds-7
[https://packages.ubuntu.com/noble/libglm-dev](https://packages.ubuntu.com/noble/libglm-dev)

and these 2 versions produced the bug described above.

I used the following script to try many different GLM versions from [https://github.com/g-truc/glm](https://github.com/g-truc/glm) repository, including versions 0.9.9.7 and 0.9.9.8 and they worked fine :

`nano try-glm-version.sh`

```
#!/bin/bash

v=$1

wget https://github.com/g-truc/glm/releases/download/${v}/glm-${v}.zip \
  && unzip glm-${v}.zip \
  && sudo cp -R glm/glm /usr/local/include/glm-${v} \
  && rm -rf glm*

cd /path/to/rubiks-cube-cracker/build

rm CMakeCache.txt 

cmake -D GLM_INCLUDE_DIR=/usr/local/include/glm-${v} ..

make -j4

cd ..

build/rubiksCube

```

`chmod +x try-glm-version.sh`

`./try-glm-version.sh 0.9.9.7`
